var dialogs = [
  ["center","Sumber dialog dikutip dari cerita Wattpad berjudul 'Kisah Romantis' oleh arvala.<br>Kunjungi cerita aslinya di : <a href='https://www.wattpad.com/405917284-kisah-romantis-chatting' target='_blank'>Kisah_Romantis</a>",""],
  ["right","Bsk jogging yuk","17:21"],
  ["left","Gk usah ngajakin kalo ujungnya php-in 😒","17:24"],
  ["right","Serius sayanh","17:24"],
  ["right","Sayanh","17:24"],
  ["right","Sayang","17:24"],
  ["left","Gak percaya!","17:27"],
  ["left","Urusin typo kamu dulu!","17:27"],
  ["right","Sayang","17:27"],
  ["left","Bodo","17:28"],
  ["right","Ciyus","17:29"],
  ["right","Yuk ktemu","17:29"],
  ["right","Besk pagi aku ke rumah","17:29"],
  ["right","Jempuy kmu jogginh","17:29"],
  ["right","Jenpuy kamu joghing","17:30"],
  ["right","Jempuy kamu jogging","17:30"],
  ["right","Asatagaaaaaa","17:30"],
  ["right","Typo","17:37"],
  ["left","Udah! Urusin typo kamu duku!","17:37"],
  ["left","Dulu","17:37"],
  ["center","Pensaran dengan kelanjutannya? Yuk langsung baca saja di cerita aslinya.<br>Kunjungi cerita aslinya di : <a href='https://www.wattpad.com/405917284-kisah-romantis-chatting' target='_blank'>Kisah_Romantis</a>",""],
];
